### PR TITLE
Refactor the exercise setup and add testing for Twofer

### PR DESCRIPTION
**Pull request by jmrunkle**

### CODE REVIEW

**Comment by jmrunkle** [comment]
Hey @Smarticles101 - I took a stab at a significant refactoring of our analyzer and added some testing for the existing codebase. This started as a desire to get the Hamming analyzer done and I realized that I needed to get this refactored first. I think I have permissions necessary to merge this myself, but a reasonable voice inside me says I should have someone like you take a look first. Cheers!

**Comment by jmrunkle** [comment]
@Smarticles101 - how strong is your preference for regular Assert? The Truth package has much easier to read and write assertions (including which one is the actual and which one is expected). For collections it has extremely nice assertions like "isEmpty" and "contains" (also "containsExactly"). The error messages are also much better with Truth than straight up Assert.

**Comment by jmrunkle** [comment]
> @Smarticles101 - how strong is your preference for regular Assert? The Truth package has much easier to read and write assertions (including which one is the actual and which one is expected). For collections it has extremely nice assertions like "isEmpty" and "contains" (also "containsExactly"). The error messages are also much better with Truth than straight up Assert.

For example, the Truth assertion for equality was able to tell me that the string representation of the two JSONObjects that I was comparing was equal, but had different instances (which made me realize that I had to use `toString()` to do the comparison).

The clarity is pretty striking:

```java
// This is really easy to get right
assertThat(actual).isEqualTo(expected);
// vs this which is easy to get wrong
assertEquals(expected, actual);

// And you get semantically meaningful assertions
assertThat(listOfStuff).hasSize(3);
// vs this
assertEquals(listOfStuff.size(), 3);
```

I have a pretty strong preference for Truth since it is a more robust API. Even the JSON unit tests get the order wrong for actual and expected: [JSONObjectTest.java](https://github.com/tdunning/open-json/blob/master/src/test/java/org/json/JSONObjectTest.java#L55) ([Assert API](http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(long,%20long)))

**Comment by Smarticles101** [comment]
@jmrunkle my preference isn't too strong. I just don't want too many packages to mix and for it to get too confusing. we can keep using Truth for now, I suppose if any problems arise we can always change it later ;)

**Comment by Smarticles101** [comment]
looks like there's some conflicts to fix before merging ;)

feel free to merge once those are resolved

**Pull request merged**
