### PR TITLE
Repair docker

### PR DESCRIPTION
**Pull request by NobbZ**
This fixes the docker build on a clean environment.

I have not tested if the image itself works.

### CODE REVIEW

**Comment by NobbZ** [comment]
Was able to test the image itself, I think, it does not yet work…

I hope I will be able to tackle this later today:

```plain
$ docker run -v $(pwd)/archive/0:/solution exercism/java-analyzer two-fer /solution
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by iHiD** [comment]
Brilliant. Thanks @NobbZ!

I'll let @exercism/java-analyzer review and merge :)

**Comment by NobbZ** [comment]
Okay, after the latest commits it seems to work. After running the command above, I got a file in the volume `analysis.json`.

**Comment by Smarticles101** [comment]
Looks good! Thanks @NobbZ, I don't have a ton of time recently

**Pull request merged**
